version: 2
updates:
- package-ecosystem: docker
  directory: "/test"
  schedule:
    interval: daily
    time: '08:00'
    timezone: America/Los_Angeles
  open-pull-requests-limit: 99
  reviewers:
  - LanikSJ
  assignees:
  - LanikSJ
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: '08:00'
    timezone: America/Los_Angeles
  open-pull-requests-limit: 99
  reviewers:
  - LanikSJ
  assignees:
  - LanikSJ
